config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  
  root 'hello#home'
  get'about', to:'hello#about'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    
    def new 
        # On récupère un nouvel article
        @article = Article.new
    end
    
    def create
        # On crée un nouvel article
        @article = Article.new(article_params)
        
        # Si l'article se modifie on affiche un message à l'utilisateur et on le redirige vers son article
        if @article.save
            flash[:success]="Article créé"
            redirect_to article_path(@article)
            
        else
            # On reste sur la page new
            render 'new'
        end
    end
    
    def show
    end
    
    def edit
    end
    
    def update
        # Si l'article se modifie on affiche un message à l'utilisateur et on le redirige vers son article
        if @article.update(article_params)
            flash[:success]="Article modifié"
            redirect_to article_path(@article)
        else
            # On reste sur la page edit
            render 'edit'
        end
    end
    
    def index
        @articles = Article.all
    end
    
    def destroy
        @article.destroy
        flash[:danger]="Article supprimé"
        redirect_to articles_path
    end

    private
        def set_article
            # On récupère l'ID de l'article
            @article = Article.find(params[:id])
        end
        
        def article_params
            params.require(:article).permit(:title, :description)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:description, :user_id)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
   def home
   end
   def about 
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<div class="row">
<%= form_for(@article, :html => {class: "form-horizontal", role: "from"}) do |f| %>

    <div class="form-group">
        <div class="col-sm-2 control-label">
            <%= f.label :title %>
        </div>
        <div class="col-sm-6">
            <%= f.text_field :title, class: "form-control", placeholder: "Titre" %>
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-2 control-label">
            <%= f.label :description %>
        </div>
        <div class="col-sm-6">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description" %>
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit :Envoyer, class: "btn btn-default" %>
        </div>
    </div>
    
<% end %>
</div>

app/views/articles/edit.html.erb
<div class="col-sm-offset-2">
    <h1>Modification de l'Article n°<%= @article.id %></h1>
</div>

<%= render 'form' %>

<div class="col-sm-offset-2">
    <%= link_to 'Retour à la liste', articles_path %> | 
    <%= link_to 'Afficher cette article', article_path(@article) %>
</div>

app/views/articles/index.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <h1>Articles</h1>
        <p><%= link_to 'Créer un article', new_article_path %></p>
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <% @articles.each do |article| %>
                <tr>
                    <td><%= article.id %></td>
                    <td><%= link_to article.title, article_path(article) %></td>
                    <td><%= truncate(article.description, length: 60) %></td>
                    <td><%= link_to 'Editer', edit_article_path(article), class: "btn btn-xs btn-primary" %></td>
                    <td><%= link_to 'Supprimer', article_path(article), method: :delete, class: "btn btn-xs btn-danger" %></td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/articles/new.html.erb
<div class="col-sm-offset-2">
    <h1>Création d'un Article</h1>
</div>

<%= render 'form' %>

<div class="col-sm-offset-2">
    <%= link_to 'Retour à la liste', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="row">
    <div class="col-xs-offset-2 col-xs-10">
        <h1>Article n°<%= @article.id %></h1>
        <h2><%= @article.title %></h2>
        
        <div class="well col-xs-6">
            <%= @article.description %>
            
            <div class="article-actions">
                <%= link_to 'Editer l\'article', edit_article_path(@article), class: "btn btn-xs btn-primary" %>
                <%= link_to 'Supprimer cette article', article_path(@article), method: :delete, class: "btn btn-xs btn-danger" %>
                <%= link_to 'Retour à la liste', articles_path, class: "btn btn-xs btn-success" %>
                
            </div>
        </div>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/hello/about.html.erb
<h1>About</h1>

app/views/hello/home.html.erb
<div class="center container">
    <div class="jumbotron">
      <h1 class="display-4">Mattltnblog</h1>
      <p class="lead">Bienvenue sur Mattltnblog.</p>
      <hr class="separateur">
      <!-- my-4 -->
      <p>Je vous souhaite une agréable visite sur ce blog.</p>
      <p class="lead">
        <a class="btn btn-success btn-lg" href="#" role="button">S'inscrire</a>
        <%= link_to 'About', about_path, class: "btn btn-success btn-lg" %>
        <%= link_to 'Blog', articles_path, class: "btn btn-success btn-lg" %>
      </p>
    </div>
</div>

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash-#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer>
        <small>
            <%= link_to 'Mattltnblog', root_path %> Copyright by <%= link_to 'Matthieu Lentin', "https://www.linkedin.com/in/matthieulentin/" %>
        </small>
        <nav>
            <ul>
                <li>
                    <%= link_to "A Propos", about_path %>
                </li>
                <li>
                    <%= link_to "Blog", articles_path %>
                </li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Mattltnblog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "A Propos", about_path %></li>
        <li><%= link_to "Blog", articles_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Créer un article", new_article_path %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Je recherche ...">
        </div>
        <button type="submit" class="btn btn-default">Rechercher</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mattltnblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<!-- 
Si on y trouve une erreur à l'entrée d'un article on vérifie qu'il il y'a une erreur
Si il y'a une erreur, on affiche tout les messages d'erreur à l'utilisateur
-->
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-6 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "erreur") %> nous avons, luke
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>